# Generated by Django 5.0.3 on 2025-02-17 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('logo', models.URLField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('employment_type', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('salary_range', models.CharField(blank=True, max_length=50, null=True)),
                ('currency', models.CharField(blank=True, max_length=10, null=True)),
                ('experience_level', models.CharField(blank=True, max_length=50, null=True)),
                ('required_skills', models.TextField(blank=True, null=True)),
                ('preferred_skills', models.TextField(blank=True, null=True)),
                ('education_level', models.CharField(max_length=100)),
                ('certifications', models.TextField(blank=True, null=True)),
                ('languages_required', models.TextField(blank=True, null=True)),
                ('years_of_experience', models.CharField(blank=True, max_length=10, null=True)),
                ('posting_date', models.DateTimeField(blank=True, null=True)),
                ('application_deadline', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
                ('benefits', models.CharField(blank=True, max_length=50, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='human_resources.company')),
            ],
        ),
    ]
