# Generated by Django 5.0.3 on 2025-02-17 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0002_company_opportunity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='company_id',
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
