# Generated by Django 5.0.3 on 2025-04-17 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0006_generatequestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
    ]
