# Generated by Django 5.0.3 on 2025-04-21 09:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0008_companyad'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
