# Generated by Django 5.0.3 on 2025-04-26 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0011_complaint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('resolved', 'Resolved')], default='new', max_length=20),
        ),
    ]
