# Generated by Django 5.0.3 on 2025-04-26 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0012_alter_complaint_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpportunityName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='title',
        ),
        migrations.AddField(
            model_name='opportunity',
            name='opportunity_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='human_resources.opportunityname'),
        ),
    ]
