# Generated by Django 5.0.3 on 2025-04-30 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0013_opportunityname_remove_opportunity_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='humanresources',
            name='company_name',
        ),
        migrations.AddField(
            model_name='humanresources',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='human_resources.company'),
        ),
    ]
