# Generated by Django 5.0.3 on 2025-05-19 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0014_remove_humanresources_company_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('free', 'Free'), ('paid', 'Paid')], max_length=100, unique=True)),
                ('job_post_limit', models.IntegerField(blank=True, null=True)),
                ('can_generate_tests', models.BooleanField(default=False)),
                ('can_schedule_interviews', models.BooleanField(default=False)),
                ('candidate_suggestions', models.CharField(choices=[('none', 'No suggestions'), ('once', 'One time'), ('always', 'Always')], default='none', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='job_posts_this_month',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='subscription_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='human_resources.subscriptionplan'),
        ),
    ]
