# Generated by Django 5.0.3 on 2025-05-30 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0016_subscriptionplan_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('remote', 'Remote'), ('on-site', 'On-site'), ('hybrid', 'Hybrid'), ('freelance', 'Freelance'), ('internship', 'Internship'), ('part-time', 'Part-time'), ('full-time', 'Full-time')], max_length=50, null=True),
        ),
    ]
