# Generated by Django 5.0.3 on 2025-06-10 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0017_alter_opportunity_employment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='opportunity_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
