# Generated by Django 5.0.3 on 2025-06-18 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0019_alter_subscriptionplan_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyad',
            name='ad_image',
            field=models.ImageField(blank=True, null=True, upload_to='ad_images/'),
        ),
    ]
