# Generated by Django 5.0.3 on 2025-06-20 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0020_companyad_ad_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companyad',
            name='ad_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
