# Generated by Django 5.2.3 on 2025-06-27 16:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0021_alter_company_logo_alter_companyad_ad_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='embedding',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=384),
        ),
    ]
