# Generated by Django 5.2.3 on 2025-07-14 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0023_interviewschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyad',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
