# Generated by Django 5.2.3 on 2025-07-14 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0024_companyad_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyad',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='human_resources.company'),
        ),
    ]
