# Generated by Django 5.2.3 on 2025-07-15 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0026_company_used_candidate_suggestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='used_candidate_suggestion',
        ),
        migrations.AddField(
            model_name='company',
            name='used_candidate_suggestions_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_candidate_suggestions',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
