# Generated by Django 5.0.3 on 2025-05-14 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devloper', '0004_user_github_link_user_linkedin_link_user_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='is_inferred',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='source_skill',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
