# Generated by Django 5.0.3 on 2025-05-25 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devloper', '0005_skill_is_inferred_skill_source_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Arabic', 'Arabic'), ('English', 'English'), ('Spanish', 'Spanish'), ('German', 'German'), ('Turkish', 'Turkish'), ('Russian', 'Russian'), ('French', 'French'), ('Chinese', 'Chinese'), ('Japanese', 'Japanese'), ('Hindi', 'Hindi'), ('Italian', 'Italian'), ('Portuguese', 'Portuguese'), ('Korean', 'Korean'), ('Persian', 'Persian'), ('Urdu', 'Urdu')], max_length=50)),
                ('level', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=6)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='devloper.resume')),
            ],
        ),
    ]
