# Generated by Django 5.2.3 on 2025-06-27 15:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devloper', '0006_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='embedding',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=384),
        ),
    ]
