# Generated by Django 5.2.3 on 2025-07-05 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devloper', '0008_developer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fcm_token',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
