# Generated by Django 5.2.3 on 2025-07-16 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devloper', '0009_user_fcm_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResumeEvaluation',
        ),
    ]
