# Generated by Django 5.2.3 on 2025-07-17 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GenerateResume', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResumeEvaluation',
        ),
    ]
